CONFIG_MAIN_STACK_SIZE=2048
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048

CONFIG_LOG=y
CONFIG_LOG_MODE_MINIMAL=y

CONFIG_PRINTK=y

CONFIG_ASSERT=y

CONFIG_NEWLIB_LIBC=y


CONFIG_RADAR_SENSOR_DISTANCE_MM=500
CONFIG_RADAR_SPEED_LIMIT_LIGHT_KMH=60
CONFIG_RADAR_SPEED_LIMIT_HEAVY_KMH=40
CONFIG_RADAR_WARNING_THRESHOLD_PERCENT=90
CONFIG_RADAR_CAMERA_FAILURE_RATE_PERCENT=10